[package]
name = "lunio_daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
lunio_core = { version = "0.1.0", path = "../core" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
